name: Clannish
main: chalk\clannish\Clannish
version: 0.1
author: ChalkPE
api: [1.4.1]

permissions:
  clannish.*:
    description: Allows player to use all features in Clannish
    default: true
    children:
      clannish.room:
        description: Allows player to use all features of chatting rooms in Clannish
        default: true