name: SnowHalation
main: SnowHalation\SnowHalation
version: 1.5-alpha
author: hm
api: [1.12.0]
load: STARTUP

commands:
 snow:
   permission: snowhalation
   description: SnowHalation control commands
   usage: /snow

permissions:
 snowhalation:
  default: true
  description: Allows commands of SnowHalation