name: PSYCHOPASS_Dominator
main: ifteam\PSYCHOPASS\PSYCHOPASS_Dominator
version: 0.5-beta
author: ifteam
api: [1.12.0]

commands:
 b:
  permission: Dominator.commands.ban
  description: Use Dominator Ban
  usage: /b <index or nickname>
 i:
  permission: Dominator.commands.ipban
  description: Use Dominator IP Ban
  usage: /i <index or nickname>
 k:
  permission: Dominator.commands.kick
  description: Use Dominator Kick
  usage: /k <index or nickname>
 s:
  permission: Dominator.commands.subnetban
  description: Use Dominator Subnetban
  usage: /s <index or nickname>
 l:
  permission: Dominator.commands.list
  description: Use Dominator List
  usage: /l
 p:
  permission: Dominator.commands.pardon
  description: Use Dominator Pardon
  usage: /p <index or nickname>

permissions:
 Dominator.commands.*:
  default: op
  description: Allows commands of Dominator
 Dominator.commands.ban:
  default: op
 Dominator.commands.ipban:
  default: op
 Dominator.commands.kick:
  default: op
 Dominator.commands.subnetban:
  default: op
 Dominator.commands.list:
  default: op
 Dominator.commands.pardon:
  default: op