---
default-home-size: 20
maximum-home-limit: 1
show-prevent-message: true
economy-enable: true
economy-home-price: 5000
economy-home-reward-price: 2500
show-opland-message: true
hour-tax-price: 4
default-prefix: '[ 서버 ]'
welcome-prefix: '[ 환영메시지 ]'
default-wall-type: 139
enable-setarea: true
...
