name: EconomyEntities
main: ifteam\EconomyEntities\EconomyEntities
author: ifteam
version : 3.7-alpha
api: [1.4.1]

permission:
 economyentities:
  default: OP
  description: Allows commands of EconomyEntities control