name: OverTheServer
main: ifteam\OverTheServer\OverTheServer
version: 0.1-Alpha
author: ifteam
api: [1.12.0]

permissions:
 overtheserver.control:
  default: OP
 overtheserver.serverconnect:
  default: true
 overtheserver.serverlist:
  default: true