minPasswordLength: 5
serverName: "PocketMine"
subjectName: "[PocketMine] 회원가입 확인메일"
encoding: euc-kr
adminEmail: ""
adminEmailHost: ""
adminEmailPort: ""
adminEmailPassword: ""
disableRegister: false
default-prefix: "[ 서버 ]"
authenticateTimeout: 60